In [3]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

In [3]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
print(arr1.shape)

(3,)


In [6]:
print(arr2.shape)

(2, 3)


In [7]:
print(arr1.size)
print(arr2.size)

3
6


In [8]:
print(arr1.dtype)
print(arr2.dtype)

int64
int64


In [12]:
print(np.zeros(3))
print(np.ones(5))

[0. 0. 0.]
[1. 1. 1. 1. 1.]


In [13]:
print(np.arange(5,10,2))

[5 7 9]


## practice

In [14]:
arr3 = np.array([6,2,-7,2,8,-2,1])
arr4 = np.array([[1,3,5],[2,4,6]])

In [17]:
print(arr3.ndim)
print(arr3.shape)
print(arr3.size)
print(arr3.dtype)

1
(7,)
7
int64


In [18]:
print(arr4.ndim)
print(arr4.shape)
print(arr4.size)
print(arr4.dtype)

2
(2, 3)
6
int64


In [19]:
arr_all_0 = np.zeros(6)
print(arr_all_0)

[0. 0. 0. 0. 0. 0.]


In [20]:
arr_all_1 = np.ones(6)
print(arr_all_1)

[1. 1. 1. 1. 1. 1.]


In [23]:
arr_even = np.arange(10,21,2)
print(arr_even)

[10 12 14 16 18 20]


In [12]:
arr5 = np.array([2,3,4,6])
arr6 = np.array([12,66,5,9])
arr7 = np.array([1,0])
arr8 = np.concatenate([arr5,arr6,arr7])
print(arr8)
print(np.sort(arr8))

[ 2  3  4  6 12 66  5  9  1  0]
[ 0  1  2  3  4  5  6  9 12 66]


In [13]:
print(arr8[0])
print(arr8[-1])
print(arr8[1:5])

2
0
[ 3  4  6 12]


In [14]:
print(arr5 + arr6)
print(arr5 - arr6)
print(arr5 * arr6)
print(arr5 / arr6)

[14 69  9 15]
[-10 -63  -1  -3]
[ 24 198  20  54]
[0.16666667 0.04545455 0.8        0.66666667]


In [16]:
print(arr5 * 3)
print(arr5 + 3)
print(arr5 - 3)
print(arr5 / 3)

[ 6  9 12 18]
[5 6 7 9]
[-1  0  1  3]
[0.66666667 1.         1.33333333 2.        ]


In [18]:
print(arr5.max())
print(arr5.min())
print(arr5.sum())
print(arr5.mean())

6
2
15
3.75


In [26]:
print(arr5[arr5>2])
print(arr5[arr5<2])
print(arr5[arr5==2])
print(arr5[(arr5>2) & (arr5 <5)])

[3 4 6]
[]
[2]
[3 4]


## NumPy练习-2